import {ComponentType,useEffect,useState} from "react";
import Home from "../app/page";
import Journal from "../app/journal/page";
import ClickToFocus from "../app/journal/click-to-focus/page";
import MedicationGuide from "../app/medication-guide/page";
import {curriculum,Lang} from "../app/journal/curriculum";
type Route={page:"home"}|{page:"journal"}|{page:"click"}|{page:"medication"}|{page:"draft",slug:string};
const getRoute=():Route=>{const path=location.hash.replace(/^#/,"")||"/";if(path==="/journal")return{page:"journal"};if(path==="/journal/click-to-focus")return{page:"click"};if(path==="/medication-guide")return{page:"medication"};if(path.startsWith("/journal/"))return{page:"draft",slug:path.split("/").pop()||""};return{page:"home"}};
function DraftArticle({slug}:{slug:string}){const item=curriculum.find(x=>x.slug===slug);const[lang,setLang]=useState<Lang>("en");if(!item)return <main className="journalArticle"><div className="articleMissing"><h1>Article not found.</h1><a href="/journal">← Journal</a></div></main>;const ko=lang==="ko";return <main className={`journalArticle ${lang}`}><header className="journalNav"><a className="brand" href="/"><span className="mark"><i/></span>DESIGN ORBIT</a><div className="journalTools"><div className="lang"><button className={lang==="en"?"on":""} onClick={()=>setLang("en")}>EN</button><span>/</span><button className={lang==="ko"?"on":""} onClick={()=>setLang("ko")}>KO</button></div><a href="/journal">← {ko?"저널 목록":"Journal index"}</a></div></header><article className="articleIntro curriculumIntro"><p className="eyebrow">ARTICLE {item.no} · {item.track}</p><h1>{item.title[lang]}</h1><p>{item.summary[lang]}</p><div className="lessonBadge"><span>THREE.JS JOURNEY</span><strong>{item.journey}</strong></div></article><section className="demoBrief"><p className="eyebrow">{ko?"작은 데모 규격":"WORKING DEMO"}</p><h2>{item.demo[lang]}</h2></section><article className="articleBody">{item.sections[lang].map(([heading,body],i)=><section key={heading}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{heading}</h2><p>{body}</p></div></section>)}</article><section className="articleEvidence"><p className="eyebrow">{ko?"포트폴리오 완료 기준":"PORTFOLIO COMPLETION"}</p><h2>{item.proof[lang]}</h2><ul><li>{ko?"재현 가능한 데모와 GitHub README":"Reproducible demo and GitHub README"}</li><li>{ko?"데스크톱·모바일 화면과 작동 영상":"Desktop/mobile captures and interaction video"}</li><li>{ko?"문제·판단·결과 설명":"Problem, decision and result"}</li><li>{ko?"회사 코드와 환자 데이터 미포함":"No company code or patient data"}</li></ul></section></main>}
export default function App(){const[route,setRoute]=useState<Route>(getRoute());useEffect(()=>{const change=()=>{setRoute(getRoute());scrollTo(0,0)};const links=(event:MouseEvent)=>{const anchor=(event.target as HTMLElement).closest("a");const href=anchor?.getAttribute("href");if(href?.startsWith("/")){event.preventDefault();location.hash=href}};addEventListener("hashchange",change);document.addEventListener("click",links);return()=>{removeEventListener("hashchange",change);document.removeEventListener("click",links)}},[]);let Page:ComponentType;if(route.page==="home")Page=Home;else if(route.page==="journal")Page=Journal;else if(route.page==="click")Page=ClickToFocus;else if(route.page==="medication")Page=MedicationGuide;else return <DraftArticle slug={route.slug}/>;return <Page/>}
